In [1]:
import sys
sys.path.append("/home/aiuser/work/userlib/BigQuant_Research_Frameworks")
from BQCN.DT.FACT.VPTA.CDAD1.CDAD1 import *

In [2]:
ed = dai.query(f"SELECT DISTINCT date FROM cn_stock_bar1d WHERE date >= '2024-01-01' ORDER BY date DESC").df()['date'].iloc[0].strftime("%Y-%m-%d")
sd = '2024-10-01'

In [3]:
data_generator = CNDT_FACT_VPTA_CDAD1(sd, ed)

In [4]:
data_generator.alpha_vpta_mavg("close", 5)

            date instrument  alpha_vpta_mavg_close_5
0     2024-10-08  159001.SZ               100.000000
1     2024-10-08  159003.SZ                99.999200
2     2024-10-08  159005.SZ                99.999600
3     2024-10-08  159150.SZ                 1.141200
4     2024-10-08  159300.SZ                 1.105894
...          ...        ...                      ...
47868 2024-11-21  588860.SH                 1.165800
47869 2024-11-21  588880.SH                 0.893876
47870 2024-11-21  588890.SH                 1.614200
47871 2024-11-21  588900.SH                 0.933400
47872 2024-11-21  588990.SH                 1.505200

[47873 rows x 3 columns]

In [5]:
data_generator.alpha_vpta_MACD()

,date,instrument,alpha_vpta_MACD_DIF_26_13_9,alpha_vpta_MACD_DEA_26_13_9,alpha_vpta_MACD_HIST_26_13_9
0,2024-10-08,159001.SZ,-0.000054,-0.000063,0.000009
1,2024-10-08,159003.SZ,-0.000108,-0.000071,-0.000038
2,2024-10-08,159005.SZ,-0.000019,-0.000079,0.000060
3,2024-10-08,159150.SZ,0.051779,0.016212,0.035567
4,2024-10-08,159300.SZ,0.044853,0.012289,0.032563
...,...,...,...,...,...
47868,2024-11-21,588860.SH,0.017908,0.024712,-0.006805
47869,2024-11-21,588880.SH,0.026284,0.033070,-0.006786
47870,2024-11-21,588890.SH,0.062336,0.078887,-0.016551
47871,2024-11-21,588900.SH,0.027941,0.035097,-0.007157
47872,2024-11-21,588990.SH,0.057078,0.072310,-0.015232

In [6]:
data_generator.alpha_vpta_PVT()

            date instrument  alpha_vpta_PVT
0     2024-10-08  159001.SZ    9.105130e+04
1     2024-10-08  159003.SZ    1.321706e+04
2     2024-10-08  159005.SZ   -5.436595e+04
3     2024-10-08  159150.SZ    1.803570e+07
4     2024-10-08  159300.SZ    3.618024e+07
...          ...        ...             ...
47868 2024-11-21  588860.SH    7.662123e+07
47869 2024-11-21  588880.SH    3.143520e+07
47870 2024-11-21  588890.SH    3.649999e+07
47871 2024-11-21  588900.SH    1.505115e+07
47872 2024-11-21  588990.SH    4.631569e+07

[47873 rows x 3 columns]