In [1]:
import sys
sys.path.append("/home/aiuser/work/userlib/BigQuant_Research_Frameworks")
from BQCN.DT.FACT.VPTA.STAD1.STAD1 import *

In [2]:
ed = dai.query(f"SELECT DISTINCT date FROM cn_stock_bar1d WHERE date >= '2024-01-01' ORDER BY date DESC").df()['date'].iloc[0].strftime("%Y-%m-%d")
sd = '2024-07-01'

In [3]:
data_generator = CNDT_FACT_VPTA_STAD1(sd, ed)

In [4]:
data_generator.alpha_vpta_mavg("close", 5)

             date instrument  alpha_vpta_mavg_close_5
0      2024-07-01  000001.SZ              1270.251172
1      2024-07-01  000002.SZ              1290.823669
2      2024-07-01  000004.SZ                42.377951
3      2024-07-01  000006.SZ               152.043991
4      2024-07-01  000007.SZ                      NaN
...           ...        ...                      ...
519572 2024-11-21  920066.BJ                47.894000
519573 2024-11-21  920088.BJ                31.024000
519574 2024-11-21  920099.BJ                36.682000
519575 2024-11-21  920111.BJ                34.238000
519576 2024-11-21  920118.BJ                28.906000

[519577 rows x 3 columns]

In [5]:
data_generator.alpha_vpta_MACD()

,date,instrument,alpha_vpta_MACD_DIF_26_13_9,alpha_vpta_MACD_DEA_26_13_9,alpha_vpta_MACD_HIST_26_13_9
0,2024-07-01,000001.SZ,-2.572843,-3.700081,1.127238
1,2024-07-01,000002.SZ,-37.572117,-23.711951,-13.860165
2,2024-07-01,000004.SZ,0.054875,-0.712321,0.767196
3,2024-07-01,000006.SZ,0.264115,-1.295160,1.559275
4,2024-07-01,000007.SZ,NaN,NaN,NaN
...,...,...,...,...,...
519572,2024-11-21,920066.BJ,NaN,NaN,NaN
519573,2024-11-21,920088.BJ,NaN,NaN,NaN
519574,2024-11-21,920099.BJ,1.501606,1.771159,-0.269553
519575,2024-11-21,920111.BJ,NaN,NaN,NaN
519576,2024-11-21,920118.BJ,1.422010,1.616505,-0.194495

In [6]:
data_generator.alpha_vpta_PVT()

             date instrument  alpha_vpta_PVT
0      2024-07-01  000001.SZ    1.284167e+09
1      2024-07-01  000002.SZ    2.063603e+09
2      2024-07-01  000004.SZ    5.758407e+07
3      2024-07-01  000006.SZ    5.363488e+08
4      2024-07-01  000007.SZ    1.023312e+08
...           ...        ...             ...
519572 2024-11-21  920066.BJ    1.091680e+05
519573 2024-11-21  920088.BJ   -5.142881e+05
519574 2024-11-21  920099.BJ    5.817290e+06
519575 2024-11-21  920111.BJ    1.011764e+07
519576 2024-11-21  920118.BJ    1.907763e+06

[519577 rows x 3 columns]

In [7]:
data_generator.alpha_vpta_RPS()

             date instrument  alpha_vpta_RPS_RPS_6
0      2024-07-01  000001.SZ           -701.645876
1      2024-07-01  000002.SZ           -278.818151
2      2024-07-01  000004.SZ          -1276.255266
3      2024-07-01  000006.SZ          -1083.622974
4      2024-07-01  000007.SZ                   NaN
...           ...        ...                   ...
519572 2024-11-21  920066.BJ            533.480848
519573 2024-11-21  920088.BJ            504.623283
519574 2024-11-21  920099.BJ            192.351625
519575 2024-11-21  920111.BJ            636.282698
519576 2024-11-21  920118.BJ            234.915819

[519577 rows x 3 columns]