In [1]:
import sys
sys.path.append("/home/aiuser/work/userlib/BigQuant_Research_Frameworks")
from BQCN.DT.FACT.VPTA.FNAD1.FNAD1 import *

In [2]:
ed = dai.query(f"SELECT DISTINCT date FROM cn_stock_bar1d WHERE date >= '2024-01-01' ORDER BY date DESC").df()['date'].iloc[0].strftime("%Y-%m-%d")
sd = '2024-10-01'

In [3]:
data_generator = CNDT_FACT_VPTA_FNAD1(sd, ed)

In [4]:
data_generator.alpha_vpta_mavg("close", 5)

            date instrument  alpha_vpta_mavg_close_5
0     2024-10-08  159001.SZ               100.000000
1     2024-10-08  159003.SZ                99.999200
2     2024-10-08  159005.SZ                99.999600
3     2024-10-08  159150.SZ                 1.141200
4     2024-10-08  159300.SZ                 1.105894
...          ...        ...                      ...
43481 2024-11-18  588860.SH                 1.192200
43482 2024-11-18  588880.SH                 0.921560
43483 2024-11-18  588890.SH                 1.661200
43484 2024-11-18  588900.SH                 0.962000
43485 2024-11-18  588990.SH                 1.547400

[43486 rows x 3 columns]

In [5]:
data_generator.alpha_vpta_MACD()

,date,instrument,alpha_vpta_MACD_DIF_26_13_9,alpha_vpta_MACD_DEA_26_13_9,alpha_vpta_MACD_HIST_26_13_9
0,2024-10-08,159001.SZ,-0.000077,-0.000098,0.000021
1,2024-10-08,159003.SZ,-0.000125,-0.000097,-0.000028
2,2024-10-08,159005.SZ,-0.000007,-0.000064,0.000057
3,2024-10-08,159150.SZ,0.050959,0.014994,0.035965
4,2024-10-08,159300.SZ,0.044190,0.011294,0.032896
...,...,...,...,...,...
43481,2024-11-18,588860.SH,0.021543,0.030934,-0.009390
43482,2024-11-18,588880.SH,0.032317,0.038448,-0.006131
43483,2024-11-18,588890.SH,0.076195,0.091357,-0.015162
43484,2024-11-18,588900.SH,0.034160,0.040811,-0.006651
43485,2024-11-18,588990.SH,0.069895,0.083732,-0.013837

In [6]:
data_generator.alpha_vpta_PVT()

            date instrument  alpha_vpta_PVT
0     2024-10-08  159001.SZ    9.105130e+04
1     2024-10-08  159003.SZ    1.321706e+04
2     2024-10-08  159005.SZ   -5.436595e+04
3     2024-10-08  159150.SZ    1.803570e+07
4     2024-10-08  159300.SZ    3.618024e+07
...          ...        ...             ...
43481 2024-11-18  588860.SH    7.305474e+07
43482 2024-11-18  588880.SH    2.955901e+07
43483 2024-11-18  588890.SH    3.563061e+07
43484 2024-11-18  588900.SH    1.322498e+07
43485 2024-11-18  588990.SH    4.504192e+07

[43486 rows x 3 columns]