In [1]:
import sys
sys.path.append("/home/aiuser/work/userlib/BigQuant_Research_Frameworks")
from BQCN.DT.FACT.VPTA.STDD1.STDD1 import *

In [2]:
ed = dai.query(f"SELECT DISTINCT date FROM cn_stock_bar1d WHERE date >= '2024-01-01' ORDER BY date DESC").df()['date'].iloc[0].strftime("%Y-%m-%d")
sd = '2024-10-01'

In [3]:
data_generator = CNDT_FACT_VPTA_STDD1(sd, ed)

In [4]:
data_generator.alpha_vpta_mavg("close", 5)

             date instrument  alpha_vpta_mavg_close_5
0      2024-10-08     101010                      NaN
1      2024-10-08     101010                      NaN
2      2024-10-08     101010                      NaN
3      2024-10-08     101010                      NaN
4      2024-10-08     101010                      NaN
...           ...        ...                      ...
166063 2024-11-18     770302                24.295638
166064 2024-11-18     770302                23.804634
166065 2024-11-18     770302                23.568224
166066 2024-11-18     770302                23.568224
166067 2024-11-18     770302                24.295638

[166068 rows x 3 columns]

In [5]:
data_generator.alpha_vpta_MACD()

,date,instrument,alpha_vpta_MACD_DIF_26_13_9,alpha_vpta_MACD_DEA_26_13_9,alpha_vpta_MACD_HIST_26_13_9
0,2024-10-08,101010,NaN,NaN,NaN
1,2024-10-08,101010,NaN,NaN,NaN
2,2024-10-08,101010,NaN,NaN,NaN
3,2024-10-08,101010,NaN,NaN,NaN
4,2024-10-08,101010,NaN,NaN,NaN
...,...,...,...,...,...
166063,2024-11-18,770302,0.513958,0.662716,-0.148758
166064,2024-11-18,770302,0.305453,0.549240,-0.243788
166065,2024-11-18,770302,0.513958,0.662716,-0.148758
166066,2024-11-18,770302,0.305453,0.549240,-0.243788
166067,2024-11-18,770302,0.400072,0.610187,-0.210115

In [6]:
data_generator.alpha_vpta_PVT()

             date instrument  alpha_vpta_PVT
0      2024-10-08     101010             NaN
1      2024-10-08     101010   -1.598746e+07
2      2024-10-08     101010    2.862328e+09
3      2024-10-08     101010             NaN
4      2024-10-08     101010   -1.598746e+07
...           ...        ...             ...
166063 2024-11-18     770302    1.120109e+07
166064 2024-11-18     770302    1.120109e+07
166065 2024-11-18     770302    1.120109e+07
166066 2024-11-18     770302    1.120109e+07
166067 2024-11-18     770302    1.120109e+07

[166068 rows x 3 columns]