In [1]:
import sys
sys.path.append("/home/aiuser/work/userlib/BigQuant_Research_Frameworks")
from BQCN.DT.FACT.VPTA.STXD1.STXD1 import *

In [2]:
ed = dai.query(f"SELECT DISTINCT date FROM cn_stock_bar1d WHERE date >= '2024-01-01' ORDER BY date DESC").df()['date'].iloc[0].strftime("%Y-%m-%d")
sd = '2024-10-01'

In [3]:
data_generator = CNDT_FACT_VPTA_STXD1(sd, ed)

In [4]:
data_generator.alpha_vpta_mavg("close", 5)

          date  instrument  alpha_vpta_mavg_close_5
0   2024-10-08   000001.SH                      NaN
1   2024-10-08   000016.SH                      NaN
2   2024-10-08   000300.SH                      NaN
3   2024-10-08   000510.SH                      NaN
4   2024-10-08   000688.SH                      NaN
..         ...         ...                      ...
385 2024-11-18  000985.CSI               4941.80186
386 2024-11-18   399001.SZ              11000.90460
387 2024-11-18   399006.SZ               2315.51806
388 2024-11-18   399330.SZ               4904.84438
389 2024-11-18   899050.BJ               1350.90640

[390 rows x 3 columns]

In [5]:
data_generator.alpha_vpta_MACD()

,date,instrument,alpha_vpta_MACD_DIF_26_13_9,alpha_vpta_MACD_DEA_26_13_9,alpha_vpta_MACD_HIST_26_13_9
0,2024-10-08,000001.SH,NaN,NaN,NaN
1,2024-10-08,000016.SH,NaN,NaN,NaN
2,2024-10-08,000300.SH,NaN,NaN,NaN
3,2024-10-08,000510.SH,NaN,NaN,NaN
4,2024-10-08,000688.SH,NaN,NaN,NaN
...,...,...,...,...,...
385,2024-11-18,000985.CSI,99.228858,NaN,NaN
386,2024-11-18,399001.SZ,205.730592,NaN,NaN
387,2024-11-18,399006.SZ,41.872111,NaN,NaN
388,2024-11-18,399330.SZ,59.773679,NaN,NaN
389,2024-11-18,899050.BJ,95.240933,NaN,NaN

In [6]:
data_generator.alpha_vpta_PVT()

          date  instrument  alpha_vpta_PVT
0   2024-10-08   000001.SH             NaN
1   2024-10-08   000016.SH             NaN
2   2024-10-08   000300.SH             NaN
3   2024-10-08   000510.SH             NaN
4   2024-10-08   000688.SH             NaN
..         ...         ...             ...
385 2024-11-18  000985.CSI   -8.382598e+07
386 2024-11-18   399001.SZ   -7.718817e+07
387 2024-11-18   399006.SZ   -5.383353e+07
388 2024-11-18   399330.SZ   -1.149927e+07
389 2024-11-18   899050.BJ    7.261470e+06

[390 rows x 3 columns]