In [1]:
import dai
import pandas as pd
from datetime import datetime, timedelta
pd.set_option('display.max_rows', None)

In [2]:
sql = """
WITH 
data_base AS (
    SELECT DISTINCT date
    FROM cn_stock_bar1m_c
    WHERE '2024-11-19 00:00:00' <= date AND date < '2024-11-20 00:00:00'
)
SELECT 
    date,
    ROW_NUMBER(date) AS date_index_minute,
FROM data_base
ORDER BY date
"""

df = dai.query(sql).df()

In [3]:
df["dt_session_trade"]   = df["date"].apply(lambda x: f"{x.strftime('%Y%m%d')}{'AM' if x.hour < 12 else 'PM'}")
df

                   date  date_index_minute dt_session_trade
0   2024-11-19 09:25:00                  1       20241119AM
1   2024-11-19 09:31:00                  2       20241119AM
2   2024-11-19 09:32:00                  3       20241119AM
3   2024-11-19 09:33:00                  4       20241119AM
4   2024-11-19 09:34:00                  5       20241119AM
5   2024-11-19 09:35:00                  6       20241119AM
6   2024-11-19 09:36:00                  7       20241119AM
7   2024-11-19 09:37:00                  8       20241119AM
8   2024-11-19 09:38:00                  9       20241119AM
9   2024-11-19 09:39:00                 10       20241119AM
10  2024-11-19 09:40:00                 11       20241119AM
11  2024-11-19 09:41:00                 12       20241119AM
12  2024-11-19 09:42:00                 13       20241119AM
13  2024-11-19 09:43:00                 14       20241119AM
14  2024-11-19 09:44:00                 15       20241119AM
15  2024-11-19 09:45:00                 16       20241119AM
16  2024-11-19 09:46:00                 17       20241119AM
17  2024-11-19 09:47:00                 18       20241119AM
18  2024-11-19 09:48:00                 19       20241119AM
19  2024-11-19 09:49:00                 20       20241119AM
20  2024-11-19 09:50:00                 21       20241119AM
21  2024-11-19 09:51:00                 22       20241119AM
22  2024-11-19 09:52:00                 23       20241119AM
23  2024-11-19 09:53:00                 24       20241119AM
24  2024-11-19 09:54:00                 25       20241119AM
25  2024-11-19 09:55:00                 26       20241119AM
26  2024-11-19 09:56:00                 27       20241119AM
27  2024-11-19 09:57:00                 28       20241119AM
28  2024-11-19 09:58:00                 29       20241119AM
29  2024-11-19 09:59:00                 30       20241119AM
30  2024-11-19 10:00:00                 31       20241119AM
31  2024-11-19 10:01:00                 32       20241119AM
32  2024-11-19 10:02:00                 33       20241119AM
33  2024-11-19 10:03:00                 34       20241119AM
34  2024-11-19 10:04:00                 35       20241119AM
35  2024-11-19 10:05:00                 36       20241119AM
36  2024-11-19 10:06:00                 37       20241119AM
37  2024-11-19 10:07:00                 38       20241119AM
38  2024-11-19 10:08:00                 39       20241119AM
39  2024-11-19 10:09:00                 40       20241119AM
40  2024-11-19 10:10:00                 41       20241119AM
41  2024-11-19 10:11:00                 42       20241119AM
42  2024-11-19 10:12:00                 43       20241119AM
43  2024-11-19 10:13:00                 44       20241119AM
44  2024-11-19 10:14:00                 45       20241119AM
45  2024-11-19 10:15:00                 46       20241119AM
46  2024-11-19 10:16:00                 47       20241119AM
47  2024-11-19 10:17:00                 48       20241119AM
48  2024-11-19 10:18:00                 49       20241119AM
49  2024-11-19 10:19:00                 50       20241119AM
50  2024-11-19 10:20:00                 51       20241119AM
51  2024-11-19 10:21:00                 52       20241119AM
52  2024-11-19 10:22:00                 53       20241119AM
53  2024-11-19 10:23:00                 54       20241119AM
54  2024-11-19 10:24:00                 55       20241119AM
55  2024-11-19 10:25:00                 56       20241119AM
56  2024-11-19 10:26:00                 57       20241119AM
57  2024-11-19 10:27:00                 58       20241119AM
58  2024-11-19 10:28:00                 59       20241119AM
59  2024-11-19 10:29:00                 60       20241119AM
60  2024-11-19 10:30:00                 61       20241119AM
61  2024-11-19 10:31:00                 62       20241119AM
62  2024-11-19 10:32:00                 63       20241119AM
63  2024-11-19 10:33:00                 64       20241119AM
64  2024-11-19 10:34:00                 65       20241119AM
65  2024-11-19 10:35:00                 66       20241119AM
66  2024-11-19 10:36:00                 67       20241119AM
67  2024-11-19 10:37:00                 68       20241119AM
68  2024-11-19 10:38:00                 69       20241119AM
69  2024-11-19 10:39:00                 70       20241119AM
70  2024-11-19 10:40:00                 71       20241119AM
71  2024-11-19 10:41:00                 72       20241119AM
72  2024-11-19 10:42:00                 73       20241119AM
73  2024-11-19 10:43:00                 74       20241119AM
74  2024-11-19 10:44:00                 75       20241119AM
75  2024-11-19 10:45:00                 76       20241119AM
76  2024-11-19 10:46:00                 77       20241119AM
77  2024-11-19 10:47:00                 78       20241119AM
78  2024-11-19 10:48:00                 79       20241119AM
79  2024-11-19 10:49:00                 80       20241119AM
80  2024-11-19 10:50:00                 81       20241119AM
81  2024-11-19 10:51:00                 82       20241119AM
82  2024-11-19 10:52:00                 83       20241119AM
83  2024-11-19 10:53:00                 84       20241119AM
84  2024-11-19 10:54:00                 85       20241119AM
85  2024-11-19 10:55:00                 86       20241119AM
86  2024-11-19 10:56:00                 87       20241119AM
87  2024-11-19 10:57:00                 88       20241119AM
88  2024-11-19 10:58:00                 89       20241119AM
89  2024-11-19 10:59:00                 90       20241119AM
90  2024-11-19 11:00:00                 91       20241119AM
91  2024-11-19 11:01:00                 92       20241119AM
92  2024-11-19 11:02:00                 93       20241119AM
93  2024-11-19 11:03:00                 94       20241119AM
94  2024-11-19 11:04:00                 95       20241119AM
95  2024-11-19 11:05:00                 96       20241119AM
96  2024-11-19 11:06:00                 97       20241119AM
97  2024-11-19 11:07:00                 98       20241119AM
98  2024-11-19 11:08:00                 99       20241119AM
99  2024-11-19 11:09:00                100       20241119AM
100 2024-11-19 11:10:00                101       20241119AM
101 2024-11-19 11:11:00                102       20241119AM
102 2024-11-19 11:12:00                103       20241119AM
103 2024-11-19 11:13:00                104       20241119AM
104 2024-11-19 11:14:00                105       20241119AM
105 2024-11-19 11:15:00                106       20241119AM
106 2024-11-19 11:16:00                107       20241119AM
107 2024-11-19 11:17:00                108       20241119AM
108 2024-11-19 11:18:00                109       20241119AM
109 2024-11-19 11:19:00                110       20241119AM
110 2024-11-19 11:20:00                111       20241119AM
111 2024-11-19 11:21:00                112       20241119AM
112 2024-11-19 11:22:00                113       20241119AM
113 2024-11-19 11:23:00                114       20241119AM
114 2024-11-19 11:24:00                115       20241119AM
115 2024-11-19 11:25:00                116       20241119AM
116 2024-11-19 11:26:00                117       20241119AM
117 2024-11-19 11:27:00                118       20241119AM
118 2024-11-19 11:28:00                119       20241119AM
119 2024-11-19 11:29:00                120       20241119AM
120 2024-11-19 11:30:00                121       20241119AM
121 2024-11-19 13:01:00                122       20241119PM
122 2024-11-19 13:02:00                123       20241119PM
123 2024-11-19 13:03:00                124       20241119PM
124 2024-11-19 13:04:00                125       20241119PM
125 2024-11-19 13:05:00                126       20241119PM
126 2024-11-19 13:06:00                127       20241119PM
127 2024-11-19 13:07:00                128       20241119PM
128 2024-11-19 13:08:00                129       20241119PM
129 2024-11-19 13:09:00                130       20241119PM
130 2024-11-19 13:10:00                131       20241119PM
131 2024-11-19 13:11:00                132       20241119PM
132 2024-11-19 13:12:00                133       20241119PM
133 2024-11-19 13:13:00                134       20241119PM
134 2024-11-19 13:14:00                135       20241119PM
135 2024-11-19 13:15:00                136       20241119PM
136 2024-11-19 13:16:00                137       20241119PM
137 2024-11-19 13:17:00                138       20241119PM
138 2024-11-19 13:18:00                139       20241119PM
139 2024-11-19 13:19:00                140       20241119PM
140 2024-11-19 13:20:00                141       20241119PM
141 2024-11-19 13:21:00                142       20241119PM
142 2024-11-19 13:22:00                143       20241119PM
143 2024-11-19 13:23:00                144       20241119PM
144 2024-11-19 13:24:00                145       20241119PM
145 2024-11-19 13:25:00                146       20241119PM
146 2024-11-19 13:26:00                147       20241119PM
147 2024-11-19 13:27:00                148       20241119PM
148 2024-11-19 13:28:00                149       20241119PM
149 2024-11-19 13:29:00                150       20241119PM
150 2024-11-19 13:30:00                151       20241119PM
151 2024-11-19 13:31:00                152       20241119PM
152 2024-11-19 13:32:00                153       20241119PM
153 2024-11-19 13:33:00                154       20241119PM
154 2024-11-19 13:34:00                155       20241119PM
155 2024-11-19 13:35:00                156       20241119PM
156 2024-11-19 13:36:00                157       20241119PM
157 2024-11-19 13:37:00                158       20241119PM
158 2024-11-19 13:38:00                159       20241119PM
159 2024-11-19 13:39:00                160       20241119PM
160 2024-11-19 13:40:00                161       20241119PM
161 2024-11-19 13:41:00                162       20241119PM
162 2024-11-19 13:42:00                163       20241119PM
163 2024-11-19 13:43:00                164       20241119PM
164 2024-11-19 13:44:00                165       20241119PM
165 2024-11-19 13:45:00                166       20241119PM
166 2024-11-19 13:46:00                167       20241119PM
167 2024-11-19 13:47:00                168       20241119PM
168 2024-11-19 13:48:00                169       20241119PM
169 2024-11-19 13:49:00                170       20241119PM
170 2024-11-19 13:50:00                171       20241119PM
171 2024-11-19 13:51:00                172       20241119PM
172 2024-11-19 13:52:00                173       20241119PM
173 2024-11-19 13:53:00                174       20241119PM
174 2024-11-19 13:54:00                175       20241119PM
175 2024-11-19 13:55:00                176       20241119PM
176 2024-11-19 13:56:00                177       20241119PM
177 2024-11-19 13:57:00                178       20241119PM
178 2024-11-19 13:58:00                179       20241119PM
179 2024-11-19 13:59:00                180       20241119PM
180 2024-11-19 14:00:00                181       20241119PM
181 2024-11-19 14:01:00                182       20241119PM
182 2024-11-19 14:02:00                183       20241119PM
183 2024-11-19 14:03:00                184       20241119PM
184 2024-11-19 14:04:00                185       20241119PM
185 2024-11-19 14:05:00                186       20241119PM
186 2024-11-19 14:06:00                187       20241119PM
187 2024-11-19 14:07:00                188       20241119PM
188 2024-11-19 14:08:00                189       20241119PM
189 2024-11-19 14:09:00                190       20241119PM
190 2024-11-19 14:10:00                191       20241119PM
191 2024-11-19 14:11:00                192       20241119PM
192 2024-11-19 14:12:00                193       20241119PM
193 2024-11-19 14:13:00                194       20241119PM
194 2024-11-19 14:14:00                195       20241119PM
195 2024-11-19 14:15:00                196       20241119PM
196 2024-11-19 14:16:00                197       20241119PM
197 2024-11-19 14:17:00                198       20241119PM
198 2024-11-19 14:18:00                199       20241119PM
199 2024-11-19 14:19:00                200       20241119PM
200 2024-11-19 14:20:00                201       20241119PM
201 2024-11-19 14:21:00                202       20241119PM
202 2024-11-19 14:22:00                203       20241119PM
203 2024-11-19 14:23:00                204       20241119PM
204 2024-11-19 14:24:00                205       20241119PM
205 2024-11-19 14:25:00                206       20241119PM
206 2024-11-19 14:26:00                207       20241119PM
207 2024-11-19 14:27:00                208       20241119PM
208 2024-11-19 14:28:00                209       20241119PM
209 2024-11-19 14:29:00                210       20241119PM
210 2024-11-19 14:30:00                211       20241119PM
211 2024-11-19 14:31:00                212       20241119PM
212 2024-11-19 14:32:00                213       20241119PM
213 2024-11-19 14:33:00                214       20241119PM
214 2024-11-19 14:34:00                215       20241119PM
215 2024-11-19 14:35:00                216       20241119PM
216 2024-11-19 14:36:00                217       20241119PM
217 2024-11-19 14:37:00                218       20241119PM
218 2024-11-19 14:38:00                219       20241119PM
219 2024-11-19 14:39:00                220       20241119PM
220 2024-11-19 14:40:00                221       20241119PM
221 2024-11-19 14:41:00                222       20241119PM
222 2024-11-19 14:42:00                223       20241119PM
223 2024-11-19 14:43:00                224       20241119PM
224 2024-11-19 14:44:00                225       20241119PM
225 2024-11-19 14:45:00                226       20241119PM
226 2024-11-19 14:46:00                227       20241119PM
227 2024-11-19 14:47:00                228       20241119PM
228 2024-11-19 14:48:00                229       20241119PM
229 2024-11-19 14:49:00                230       20241119PM
230 2024-11-19 14:50:00                231       20241119PM
231 2024-11-19 14:51:00                232       20241119PM
232 2024-11-19 14:52:00                233       20241119PM
233 2024-11-19 14:53:00                234       20241119PM
234 2024-11-19 14:54:00                235       20241119PM
235 2024-11-19 14:55:00                236       20241119PM
236 2024-11-19 14:56:00                237       20241119PM
237 2024-11-19 14:57:00                238       20241119PM
238 2024-11-19 14:58:00                239       20241119PM
239 2024-11-19 14:59:00                240       20241119PM
240 2024-11-19 15:00:00                241       20241119PM

In [4]:
def get_dt_hour_trade(dt):
    if dt.time() >= pd.Timestamp("09:00").time() and dt.time() <= pd.Timestamp("10:30").time():
        return f"{dt.strftime('%Y%m%d')}1"
    elif dt.time() > pd.Timestamp("10:30").time() and dt.time() <= pd.Timestamp("11:30").time():
        return f"{dt.strftime('%Y%m%d')}2"
    elif dt.time() > pd.Timestamp("13:00").time() and dt.time() <= pd.Timestamp("14:00").time():
        return f"{dt.strftime('%Y%m%d')}3"
    elif dt.time() > pd.Timestamp("14:00").time() and dt.time() <= pd.Timestamp("15:00").time():
        return f"{dt.strftime('%Y%m%d')}4"
    else:
        return None

df["dt_hour_trade"] = df["date"].apply(get_dt_hour_trade)
df

                   date  date_index_minute dt_session_trade dt_hour_trade
0   2024-11-19 09:25:00                  1       20241119AM     202411191
1   2024-11-19 09:31:00                  2       20241119AM     202411191
2   2024-11-19 09:32:00                  3       20241119AM     202411191
3   2024-11-19 09:33:00                  4       20241119AM     202411191
4   2024-11-19 09:34:00                  5       20241119AM     202411191
5   2024-11-19 09:35:00                  6       20241119AM     202411191
6   2024-11-19 09:36:00                  7       20241119AM     202411191
7   2024-11-19 09:37:00                  8       20241119AM     202411191
8   2024-11-19 09:38:00                  9       20241119AM     202411191
9   2024-11-19 09:39:00                 10       20241119AM     202411191
10  2024-11-19 09:40:00                 11       20241119AM     202411191
11  2024-11-19 09:41:00                 12       20241119AM     202411191
12  2024-11-19 09:42:00                 13       20241119AM     202411191
13  2024-11-19 09:43:00                 14       20241119AM     202411191
14  2024-11-19 09:44:00                 15       20241119AM     202411191
15  2024-11-19 09:45:00                 16       20241119AM     202411191
16  2024-11-19 09:46:00                 17       20241119AM     202411191
17  2024-11-19 09:47:00                 18       20241119AM     202411191
18  2024-11-19 09:48:00                 19       20241119AM     202411191
19  2024-11-19 09:49:00                 20       20241119AM     202411191
20  2024-11-19 09:50:00                 21       20241119AM     202411191
21  2024-11-19 09:51:00                 22       20241119AM     202411191
22  2024-11-19 09:52:00                 23       20241119AM     202411191
23  2024-11-19 09:53:00                 24       20241119AM     202411191
24  2024-11-19 09:54:00                 25       20241119AM     202411191
25  2024-11-19 09:55:00                 26       20241119AM     202411191
26  2024-11-19 09:56:00                 27       20241119AM     202411191
27  2024-11-19 09:57:00                 28       20241119AM     202411191
28  2024-11-19 09:58:00                 29       20241119AM     202411191
29  2024-11-19 09:59:00                 30       20241119AM     202411191
30  2024-11-19 10:00:00                 31       20241119AM     202411191
31  2024-11-19 10:01:00                 32       20241119AM     202411191
32  2024-11-19 10:02:00                 33       20241119AM     202411191
33  2024-11-19 10:03:00                 34       20241119AM     202411191
34  2024-11-19 10:04:00                 35       20241119AM     202411191
35  2024-11-19 10:05:00                 36       20241119AM     202411191
36  2024-11-19 10:06:00                 37       20241119AM     202411191
37  2024-11-19 10:07:00                 38       20241119AM     202411191
38  2024-11-19 10:08:00                 39       20241119AM     202411191
39  2024-11-19 10:09:00                 40       20241119AM     202411191
40  2024-11-19 10:10:00                 41       20241119AM     202411191
41  2024-11-19 10:11:00                 42       20241119AM     202411191
42  2024-11-19 10:12:00                 43       20241119AM     202411191
43  2024-11-19 10:13:00                 44       20241119AM     202411191
44  2024-11-19 10:14:00                 45       20241119AM     202411191
45  2024-11-19 10:15:00                 46       20241119AM     202411191
46  2024-11-19 10:16:00                 47       20241119AM     202411191
47  2024-11-19 10:17:00                 48       20241119AM     202411191
48  2024-11-19 10:18:00                 49       20241119AM     202411191
49  2024-11-19 10:19:00                 50       20241119AM     202411191
50  2024-11-19 10:20:00                 51       20241119AM     202411191
51  2024-11-19 10:21:00                 52       20241119AM     202411191
52  2024-11-19 10:22:00                 53       20241119AM     202411191
53  2024-11-19 10:23:00                 54       20241119AM     202411191
54  2024-11-19 10:24:00                 55       20241119AM     202411191
55  2024-11-19 10:25:00                 56       20241119AM     202411191
56  2024-11-19 10:26:00                 57       20241119AM     202411191
57  2024-11-19 10:27:00                 58       20241119AM     202411191
58  2024-11-19 10:28:00                 59       20241119AM     202411191
59  2024-11-19 10:29:00                 60       20241119AM     202411191
60  2024-11-19 10:30:00                 61       20241119AM     202411191
61  2024-11-19 10:31:00                 62       20241119AM     202411192
62  2024-11-19 10:32:00                 63       20241119AM     202411192
63  2024-11-19 10:33:00                 64       20241119AM     202411192
64  2024-11-19 10:34:00                 65       20241119AM     202411192
65  2024-11-19 10:35:00                 66       20241119AM     202411192
66  2024-11-19 10:36:00                 67       20241119AM     202411192
67  2024-11-19 10:37:00                 68       20241119AM     202411192
68  2024-11-19 10:38:00                 69       20241119AM     202411192
69  2024-11-19 10:39:00                 70       20241119AM     202411192
70  2024-11-19 10:40:00                 71       20241119AM     202411192
71  2024-11-19 10:41:00                 72       20241119AM     202411192
72  2024-11-19 10:42:00                 73       20241119AM     202411192
73  2024-11-19 10:43:00                 74       20241119AM     202411192
74  2024-11-19 10:44:00                 75       20241119AM     202411192
75  2024-11-19 10:45:00                 76       20241119AM     202411192
76  2024-11-19 10:46:00                 77       20241119AM     202411192
77  2024-11-19 10:47:00                 78       20241119AM     202411192
78  2024-11-19 10:48:00                 79       20241119AM     202411192
79  2024-11-19 10:49:00                 80       20241119AM     202411192
80  2024-11-19 10:50:00                 81       20241119AM     202411192
81  2024-11-19 10:51:00                 82       20241119AM     202411192
82  2024-11-19 10:52:00                 83       20241119AM     202411192
83  2024-11-19 10:53:00                 84       20241119AM     202411192
84  2024-11-19 10:54:00                 85       20241119AM     202411192
85  2024-11-19 10:55:00                 86       20241119AM     202411192
86  2024-11-19 10:56:00                 87       20241119AM     202411192
87  2024-11-19 10:57:00                 88       20241119AM     202411192
88  2024-11-19 10:58:00                 89       20241119AM     202411192
89  2024-11-19 10:59:00                 90       20241119AM     202411192
90  2024-11-19 11:00:00                 91       20241119AM     202411192
91  2024-11-19 11:01:00                 92       20241119AM     202411192
92  2024-11-19 11:02:00                 93       20241119AM     202411192
93  2024-11-19 11:03:00                 94       20241119AM     202411192
94  2024-11-19 11:04:00                 95       20241119AM     202411192
95  2024-11-19 11:05:00                 96       20241119AM     202411192
96  2024-11-19 11:06:00                 97       20241119AM     202411192
97  2024-11-19 11:07:00                 98       20241119AM     202411192
98  2024-11-19 11:08:00                 99       20241119AM     202411192
99  2024-11-19 11:09:00                100       20241119AM     202411192
100 2024-11-19 11:10:00                101       20241119AM     202411192
101 2024-11-19 11:11:00                102       20241119AM     202411192
102 2024-11-19 11:12:00                103       20241119AM     202411192
103 2024-11-19 11:13:00                104       20241119AM     202411192
104 2024-11-19 11:14:00                105       20241119AM     202411192
105 2024-11-19 11:15:00                106       20241119AM     202411192
106 2024-11-19 11:16:00                107       20241119AM     202411192
107 2024-11-19 11:17:00                108       20241119AM     202411192
108 2024-11-19 11:18:00                109       20241119AM     202411192
109 2024-11-19 11:19:00                110       20241119AM     202411192
110 2024-11-19 11:20:00                111       20241119AM     202411192
111 2024-11-19 11:21:00                112       20241119AM     202411192
112 2024-11-19 11:22:00                113       20241119AM     202411192
113 2024-11-19 11:23:00                114       20241119AM     202411192
114 2024-11-19 11:24:00                115       20241119AM     202411192
115 2024-11-19 11:25:00                116       20241119AM     202411192
116 2024-11-19 11:26:00                117       20241119AM     202411192
117 2024-11-19 11:27:00                118       20241119AM     202411192
118 2024-11-19 11:28:00                119       20241119AM     202411192
119 2024-11-19 11:29:00                120       20241119AM     202411192
120 2024-11-19 11:30:00                121       20241119AM     202411192
121 2024-11-19 13:01:00                122       20241119PM     202411193
122 2024-11-19 13:02:00                123       20241119PM     202411193
123 2024-11-19 13:03:00                124       20241119PM     202411193
124 2024-11-19 13:04:00                125       20241119PM     202411193
125 2024-11-19 13:05:00                126       20241119PM     202411193
126 2024-11-19 13:06:00                127       20241119PM     202411193
127 2024-11-19 13:07:00                128       20241119PM     202411193
128 2024-11-19 13:08:00                129       20241119PM     202411193
129 2024-11-19 13:09:00                130       20241119PM     202411193
130 2024-11-19 13:10:00                131       20241119PM     202411193
131 2024-11-19 13:11:00                132       20241119PM     202411193
132 2024-11-19 13:12:00                133       20241119PM     202411193
133 2024-11-19 13:13:00                134       20241119PM     202411193
134 2024-11-19 13:14:00                135       20241119PM     202411193
135 2024-11-19 13:15:00                136       20241119PM     202411193
136 2024-11-19 13:16:00                137       20241119PM     202411193
137 2024-11-19 13:17:00                138       20241119PM     202411193
138 2024-11-19 13:18:00                139       20241119PM     202411193
139 2024-11-19 13:19:00                140       20241119PM     202411193
140 2024-11-19 13:20:00                141       20241119PM     202411193
141 2024-11-19 13:21:00                142       20241119PM     202411193
142 2024-11-19 13:22:00                143       20241119PM     202411193
143 2024-11-19 13:23:00                144       20241119PM     202411193
144 2024-11-19 13:24:00                145       20241119PM     202411193
145 2024-11-19 13:25:00                146       20241119PM     202411193
146 2024-11-19 13:26:00                147       20241119PM     202411193
147 2024-11-19 13:27:00                148       20241119PM     202411193
148 2024-11-19 13:28:00                149       20241119PM     202411193
149 2024-11-19 13:29:00                150       20241119PM     202411193
150 2024-11-19 13:30:00                151       20241119PM     202411193
151 2024-11-19 13:31:00                152       20241119PM     202411193
152 2024-11-19 13:32:00                153       20241119PM     202411193
153 2024-11-19 13:33:00                154       20241119PM     202411193
154 2024-11-19 13:34:00                155       20241119PM     202411193
155 2024-11-19 13:35:00                156       20241119PM     202411193
156 2024-11-19 13:36:00                157       20241119PM     202411193
157 2024-11-19 13:37:00                158       20241119PM     202411193
158 2024-11-19 13:38:00                159       20241119PM     202411193
159 2024-11-19 13:39:00                160       20241119PM     202411193
160 2024-11-19 13:40:00                161       20241119PM     202411193
161 2024-11-19 13:41:00                162       20241119PM     202411193
162 2024-11-19 13:42:00                163       20241119PM     202411193
163 2024-11-19 13:43:00                164       20241119PM     202411193
164 2024-11-19 13:44:00                165       20241119PM     202411193
165 2024-11-19 13:45:00                166       20241119PM     202411193
166 2024-11-19 13:46:00                167       20241119PM     202411193
167 2024-11-19 13:47:00                168       20241119PM     202411193
168 2024-11-19 13:48:00                169       20241119PM     202411193
169 2024-11-19 13:49:00                170       20241119PM     202411193
170 2024-11-19 13:50:00                171       20241119PM     202411193
171 2024-11-19 13:51:00                172       20241119PM     202411193
172 2024-11-19 13:52:00                173       20241119PM     202411193
173 2024-11-19 13:53:00                174       20241119PM     202411193
174 2024-11-19 13:54:00                175       20241119PM     202411193
175 2024-11-19 13:55:00                176       20241119PM     202411193
176 2024-11-19 13:56:00                177       20241119PM     202411193
177 2024-11-19 13:57:00                178       20241119PM     202411193
178 2024-11-19 13:58:00                179       20241119PM     202411193
179 2024-11-19 13:59:00                180       20241119PM     202411193
180 2024-11-19 14:00:00                181       20241119PM     202411193
181 2024-11-19 14:01:00                182       20241119PM     202411194
182 2024-11-19 14:02:00                183       20241119PM     202411194
183 2024-11-19 14:03:00                184       20241119PM     202411194
184 2024-11-19 14:04:00                185       20241119PM     202411194
185 2024-11-19 14:05:00                186       20241119PM     202411194
186 2024-11-19 14:06:00                187       20241119PM     202411194
187 2024-11-19 14:07:00                188       20241119PM     202411194
188 2024-11-19 14:08:00                189       20241119PM     202411194
189 2024-11-19 14:09:00                190       20241119PM     202411194
190 2024-11-19 14:10:00                191       20241119PM     202411194
191 2024-11-19 14:11:00                192       20241119PM     202411194
192 2024-11-19 14:12:00                193       20241119PM     202411194
193 2024-11-19 14:13:00                194       20241119PM     202411194
194 2024-11-19 14:14:00                195       20241119PM     202411194
195 2024-11-19 14:15:00                196       20241119PM     202411194
196 2024-11-19 14:16:00                197       20241119PM     202411194
197 2024-11-19 14:17:00                198       20241119PM     202411194
198 2024-11-19 14:18:00                199       20241119PM     202411194
199 2024-11-19 14:19:00                200       20241119PM     202411194
200 2024-11-19 14:20:00                201       20241119PM     202411194
201 2024-11-19 14:21:00                202       20241119PM     202411194
202 2024-11-19 14:22:00                203       20241119PM     202411194
203 2024-11-19 14:23:00                204       20241119PM     202411194
204 2024-11-19 14:24:00                205       20241119PM     202411194
205 2024-11-19 14:25:00                206       20241119PM     202411194
206 2024-11-19 14:26:00                207       20241119PM     202411194
207 2024-11-19 14:27:00                208       20241119PM     202411194
208 2024-11-19 14:28:00                209       20241119PM     202411194
209 2024-11-19 14:29:00                210       20241119PM     202411194
210 2024-11-19 14:30:00                211       20241119PM     202411194
211 2024-11-19 14:31:00                212       20241119PM     202411194
212 2024-11-19 14:32:00                213       20241119PM     202411194
213 2024-11-19 14:33:00                214       20241119PM     202411194
214 2024-11-19 14:34:00                215       20241119PM     202411194
215 2024-11-19 14:35:00                216       20241119PM     202411194
216 2024-11-19 14:36:00                217       20241119PM     202411194
217 2024-11-19 14:37:00                218       20241119PM     202411194
218 2024-11-19 14:38:00                219       20241119PM     202411194
219 2024-11-19 14:39:00                220       20241119PM     202411194
220 2024-11-19 14:40:00                221       20241119PM     202411194
221 2024-11-19 14:41:00                222       20241119PM     202411194
222 2024-11-19 14:42:00                223       20241119PM     202411194
223 2024-11-19 14:43:00                224       20241119PM     202411194
224 2024-11-19 14:44:00                225       20241119PM     202411194
225 2024-11-19 14:45:00                226       20241119PM     202411194
226 2024-11-19 14:46:00                227       20241119PM     202411194
227 2024-11-19 14:47:00                228       20241119PM     202411194
228 2024-11-19 14:48:00                229       20241119PM     202411194
229 2024-11-19 14:49:00                230       20241119PM     202411194
230 2024-11-19 14:50:00                231       20241119PM     202411194
231 2024-11-19 14:51:00                232       20241119PM     202411194
232 2024-11-19 14:52:00                233       20241119PM     202411194
233 2024-11-19 14:53:00                234       20241119PM     202411194
234 2024-11-19 14:54:00                235       20241119PM     202411194
235 2024-11-19 14:55:00                236       20241119PM     202411194
236 2024-11-19 14:56:00                237       20241119PM     202411194
237 2024-11-19 14:57:00                238       20241119PM     202411194
238 2024-11-19 14:58:00                239       20241119PM     202411194
239 2024-11-19 14:59:00                240       20241119PM     202411194
240 2024-11-19 15:00:00                241       20241119PM     202411194